### ISSUE TITLE
telphone number is incorrect

### ISSUE THREAD

**Issue by sunjido** [Chamnol007/03Restaurant#5]
Change telephone numbers are 012-345-7890 and 098-765-4321 respectively.

**Comment by sunjido** [comment]
Find 3 news photo for web also.

**Comment by sunjido** [comment]
And then Please at the main course section, no longer serve Vegetarian and Poultry dishes. 
Price shown in entire is incorrect replace be $. And then tell another customer the coupon can be redeemed only on side also change the year to 2018

**Comment by Chamnol007** [comment]
@pakarat5022 let do it together

**Comment by pakarat5022** [comment]
OK

**Comment by pakarat5022** [comment]
i'm finish

**Comment by Chamnol007** [comment]
good job Bob
