### ISSUE TITLE
change all of this 

### ISSUE THREAD

**Issue by sunjido** [Chamnol007/03Restaurant#6]
1. Delivery service is delegated to Food panda. So, it is no longer a special offer. Remove it from the special offer page and provide the information about Food panda instead. 
2. Online menu is no longer available, remove any of the corresponding records from the website. 
3. In the front page and special offers page, the 50% discount is incorrect. It should be 20%. (Priority = High) 
4. The booking can be now made up to 48 hours in advance. 
5. Change the address to 239 Huaykaew Rd., Suthep, Muang, Chiang Mai 50200 
6. All the texts are not suited to Charlie’s taste, change them all to Arial. 
7. A psychologist told Charlie that the main color scheme of a restaurant should be in red, so he insists the team to alter the color for the entire site. 
8. The 12.5% under the booking info is reduced to 7%. 
9. “Cancellations if possible should be made 24 hours in advance” needed to be changed to “Cancellations must be made at least 24 hours in advance” 
10. Remove all the email from the website.

**Comment by Chamnol007** [comment]
@pakarat5022 your works again

**Comment by Chamnol007** [comment]
Make it as soon as possible

**Comment by pakarat5022** [comment]
OK

**Comment by Chamnol007** [comment]
I believe in u

**Comment by pakarat5022** [comment]
I'm finish

**Comment by Chamnol007** [comment]
@pakarat5022 good job well done

**Comment by sunjido** [comment]
Good jobs. Well done!! I will give you much bonus this jobs.
